# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MTN CI #^ Nombre del workflow, se puede poner cualquier nombre

on:
  push:
    branches: ["develop"]

jobs:
  build-mtn: #^ Job 1, aca se pede definir el nombre del job, se puede poner cualquier nombre
    runs-on: ubuntu-latest #^ Propiedad que indica el sistema operativo en el que se ejecutara el job, No es buena practica poner el latest, se debe poner la version especifica

    # strategy:
    #   matrix:
    #     node-version: [18.x, 20.x, 22.x]

    steps:
      - name: "Hello World mtn"
        run: echo "Hello World mtn !!!"
      - name: "Fecha y Hora"
        run: date
      - name: "Listar directorio"
        run: ls -la

      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #   with:
      #     cache: "npm"
      # - run: npm ci --legacy-peer-deps --no-fund --no-audit
      # - run: npm run lint
      # - run: npm run test
      # - run: npm run build
